const WatchListActionTypes = {
    FETCH_WATCH_LIST_START: 'FETCH_WATCH_LIST_START',
    FETCH_WATCH_LIST_SUCCESS: 'FETCH_WATCH_LIST_SUCCESS',
    FETCH_WATCH_LIST_FAILER: 'FETCH_WATCH_LIST_FAILER'
}

export default WatchListActionTypes;